# Build image for ingesting data
# docker build -t ny_taxi_ingest:v001 .
# 
# Run container
# URL="https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.parquet"
# 
# docker run -it \
#   --network=pgsql_compose_pg-network \
#   --name ingestion \
#   ny_taxi_ingest:v001 \
#     --user=root \
#     --password=root \
#     --host=pg-database \
#     --port=5432 \
#     --db=ny_taxi \
#     --table_name=yellow_taxi_data \
#     --url=${URL}

FROM python:3.9.1

RUN apt-get install wget
RUN pip install pandas numpy pyarrow sqlalchemy psycopg2

WORKDIR /app
COPY ny_yellow_ingest.py ny_yellow_ingest.py

ENTRYPOINT [ "python", "ny_yellow_ingest.py" ]