FROM python:3.9.1

RUN apt-get install wget
RUN pip install pandas numpy pyarrow sqlalchemy psycopg2

WORKDIR /app
COPY ny_yellow_ingest.py ny_yellow_ingest.py

ENTRYPOINT [ "python", "ny_yellow_ingest.py" ]