# Build image for ingesting data
# docker build -f docker/dockerfile -t ny_taxi_ingest:v002 .
# 
# Run container
# URL="https://d37ci6vzurychx.cloudfront.net/trip-data/yellow_tripdata_2021-01.parquet"
# 
# docker run -it \
#   --network=pgsql_compose_pg-network \
#   --name yellow_taxi_ingest \
#   ny_taxi_ingest:v002 \
#     --user=root \
#     --password=root \
#     --host=pgdatabase \
#     --port=5432 \
#     --db=ny_taxi \
#     --tb=yellow_taxi_data \
#     --url=${URL}

FROM python:3.9.1

RUN apt-get install wget
RUN pip install pandas pyarrow sqlalchemy psycopg2

WORKDIR /app
COPY ./pipelines/python/data-loading.py data-loading.py

ENTRYPOINT [ "python", "data-loading.py" ]